### ISSUE TITLE
Odyssey _config

### ISSUE THREAD

**Issue by NinaChang1107** [HIPS/hypergrad#5]
Hi, 
    I have done everything as what readme.md said. It works well.
    But when i run something in /hypergrad/experiments, error occurs:

nina@nina-virtual-machine:~/code/hypergrad/experiments/Feb_1_learning_alphabet_corr/1$ python experiment.py
Traceback (most recent call last):
  File "experiment.py", line 13, in <module>
    from hypergrad.odyssey import omap
  File "/home/nina/anaconda2/lib/python2.7/site-packages/hypergrad-1.0-py2.7.egg/hypergrad/odyssey.py", line 25, in <module>
    from odyssey_config import root_working_dir, slurm_options
ImportError: No module named odyssey_config

I don't know how odyssey and odyssey_config works, and can't get the mining  of the following text in odyssey.py.

Can u tell me how to make the code works step by step?

Thank u very much!

""" Provides `omap`, which works like Python's `map`, but farms out to
Odyssey. Here's how to use it:
* Make a scratch space directory on your Odyssey account (e.g. ~/tmp/)
* Mount this (or the whole Odyssey home dir) on your local machine with sshfs
* Make an `odyssey_config.py` that points to it (look at `odyssey_config_example.py`)
* On Odyssey, run "python -m slurm_job_watcher" from within the tmp directory
* Run a script (e.g. test_odyssey.py) from your local machine...it should just work

**Comment by duvenaud** [comment]
Just ignore all the Odyssey stuff - it was for interfacing with the local compute cluster.  I think you can just replace omap with map.
